##################################
#### Generated by {component} ####
########## Do not edit  ##########
##################################

#' Generated JavaScript Dependency
#' 
#' @keywords internal
testDependency <- \(){
	htmltools::htmlDependency(
		name = "test",
		version = "0.0.0.9000",
		src = "test",
		script = "test.js",
		stylesheet = "test.css",
		package = "component"
	)
}

#' Test generated UI
#' 
#' @param id ID of module
#' 
#' @keywords internal
test_ui <- \(id){
	ns <- shiny::NS(id)
	shiny::tagList(
		testDependency(),
		.test_ui(ns)
	)
}

#' Test generated server
#' 
#' @param id ID of module
#' 
#' @keywords internal
test_server <- \(id){
	shiny::moduleServer(id, .test_server)
}

