##################################
##### Generated by Component #####
########## Do not edit  ##########
##################################
#' Generated JavaScript Dependency
#' @keywords internal
testDependency <- \(){
	htmltools::htmlDependency(
		name = "test",
		version = "0.0.0.9000",
		src = "test",
		script = "test.js",
		stylesheet = "test.css",
		package = "component"
	)
}
