pkg_file <- \(...){
  system.file(..., package = "component")
}

dir_exists <- function(...){
  file.path(...) |>
    dir.exists()
}

dir_create_if_missing <- function(...) {
  if(dir_exists(...))
    return()

  dir.create(file.path(...))
}

file_exists <- function(...){
  file.path(...) |>
    file.exists()
}

file_create_if_missing <- function(...) {
  if(file_exists(...))
    return()

  file.create(file.path(...))
}

remove_file_if_exists <- function(...){
  if(!file_exists(...))
    return()

  file.remove(...)
}

make_component_fn <- function(name, what) {
  paste0(name, "_", what)
}

get_package_name <- function(){
  pkg <- readLines("DESCRIPTION")[1]
  gsub("Package: ", "", pkg) |> trimws()
}

make_write_lines <- \(file){
  CON <- file(file, "a")

  list(
    w = \(...){
      paste0(...) |>
        writeLines(con = CON)
    },
    c = \(){
      close(CON)
    }
  )
}

make_file <- function(component, extension) {
  sprintf(
    "%s.%s",
    component,
    extension
  )
}

make_output_file <- function(component, extension, dir) {
  sprintf(
    "%s/%s",
    dir,
    make_file(
      component,
      extension
    )
  )
}

make_dependency <- function(params) {
  wl <- make_write_lines(params$path_r)

  on.exit(wl$c())

  pkg <- get_package_name()

  wl$w("##################################")
  wl$w("##### Generated by Component #####")
  wl$w("########## Do not edit  ##########")
  wl$w("##################################")
  wl$w("\n")
  wl$w("#' Generated JavaScript Dependency")
  wl$w("#' @keywords internal")
  wl$w(params$component, "Dependency <- \\(){")
  wl$w("\thtmltools::htmlDependency(")
  wl$w('\t\tname = "', params$component, '",')
  wl$w('\t\tversion = "', utils::packageVersion(pkg), '",')
  wl$w('\t\tsrc = "', params$component, '",')
  wl$w('\t\tscript = "', params$file_js, '",')
  wl$w('\t\tstylesheet = "', params$file_css, '",')
  wl$w('\t\tpackage = "', pkg, '"')
  wl$w("\t)")
  wl$w("}")
}
