pkg_file <- \(...){
  system.file(..., package = "component")
}

dir_exists <- function(...){
  file.path(...) |>
    dir.exists()
}

dir_create_if_missing <- function(...) {
  if(dir_exists(...))
    return()

  dir.create(file.path(...))
}

file_exists <- function(...){
  file.path(...) |>
    file.exists()
}

file_create_if_missing <- function(...) {
  if(file_exists(...))
    return()

  file.create(file.path(...))
}

remove_file_if_exists <- function(...){
  if(!file_exists(...))
    return()

  file.remove(...)
}

make_component_fn <- function(name, what) {
  paste0(".", name, "_", what)
}

get_package_name <- function(){
  pkg <- readLines("DESCRIPTION")[1]
  gsub("Package: ", "", pkg) |> trimws()
}

make_write_lines <- \(file){
  CON <- file(file, "a")

  list(
    w = \(...){
      paste0(...) |>
        writeLines(con = CON)
    },
    c = \(){
      close(CON)
    }
  )
}

make_file <- function(component, extension) {
  sprintf(
    "%s.%s",
    component,
    extension
  )
}

make_output_file <- function(component, extension, dir) {
  sprintf(
    "%s/%s",
    dir,
    make_file(
      component,
      extension
    )
  )
}

make_ui <- function(params) {
  wl <- make_write_lines(params$path_r)
  on.exit(wl$c())

  wl$w("#' ", tools::toTitleCase(params$component), " generated UI")
  wl$w("#' ")
  wl$w("#' UI generated from: .", params$component, "_ui()")
  wl$w("#' ")
  wl$w("#' @param id ID of module")
  wl$w("#' @param ... Any arguments to pass to .", params$component, "_ui()")
  wl$w("#' ")
  wl$w("#' @keywords internal")
  wl$w(params$component, "_ui <- \\(id, ...){")
  wl$w("\tns <- shiny::NS(id)")
  wl$w("\tshiny::tagList(")
  wl$w("\t\tshiny::tags$head(")
  wl$w("\t\t\tshiny::tags$style(shiny::HTML(.", params$component, "_css(...) |> component::namespace(ns, list(...)))),")
  wl$w("\t\t\tshiny::tags$script(shiny::HTML(.", params$component, "_javascript(...) |> (\\(.) c(\"$(() => {\", ., \"})\"))() |> component::namespace(ns, list(...))))")
  wl$w("\t\t),")
  wl$w("\t\t.", params$component, "_ui(ns, ...)")
  wl$w("\t)")
  wl$w("}")
  wl$w("")
}

make_server <- function(params) {
  wl <- make_write_lines(params$path_r)
  on.exit(wl$c())

  wl$w("#' ", tools::toTitleCase(params$component), " generated server")
  wl$w("#' ")
  wl$w("#' Server generated from: .", params$component, "_server()")
  wl$w("#' ")
  wl$w("#' @param id ID of module")
  wl$w("#' @param ... Any arguments to pass to .", params$component, "_server()")
  wl$w("#' ")
  wl$w("#' @keywords internal")
  wl$w(params$component, "_server <- \\(id, ...){")
  wl$w("\tfn <- \\(input, output, session) {", params$component, "_server(input, output, session, ...)}")
  wl$w("\tshiny::moduleServer(id, .", params$component, "_server)")
  wl$w("}")
  wl$w("")
}

make_dependency <- function(params) {
  wl <- make_write_lines(params$path_r)
  on.exit(wl$c())

  pkg <- get_package_name()

  wl$w("##################################")
  wl$w("#### Generated by {component} ####")
  wl$w("########## Do not edit  ##########")
  wl$w("##################################")
  wl$w("")
  wl$w("#' ", tools::toTitleCase(params$component), " generated dependencies")
  wl$w("#' ")
  wl$w("#' JavaScript and CSS dependencies for component: ", params$component)
  wl$w("#' ")
  wl$w("#' @keywords internal")
  wl$w(params$component, "Dependency <- \\(){")
  wl$w("\thtmltools::htmlDependency(")
  wl$w('\t\tname = "', params$component, '",')
  wl$w('\t\tversion = "', utils::packageVersion(pkg), '",')
  wl$w('\t\tsrc = "', params$component, '",')
  wl$w('\t\tscript = "', params$file_js, '",')
  wl$w('\t\tstylesheet = "', params$file_css, '",')
  wl$w('\t\tpackage = "', pkg, '"')
  wl$w("\t)")
  wl$w("}")
  wl$w("")
}

